server {
    listen 80;

    client_max_body_size 15m;

    location / {
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Request-Id $request_id;
    }

    location /api/ {
        proxy_pass http://request-management-service:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Request-Id $request_id;
    }

    location /health {
        proxy_pass http://request-management-service:8000/health;
    }
}
